### ISSUE TITLE
Modifying the class list for existing synthetic data

### ISSUE THREAD

**Issue by villanuevab** [umautobots/driving-in-the-matrix#2]
Is it possible to modify the class list of the provided data? I would like to add, for example, classes for `stopSign` and `pedestrianCrossingSign`. I saw https://github.com/umautobots/GTAVisionExport/tree/master/native which would allow me to capture/generate new synthetic data, but I am specifically wondering if the existing data can be modified programmatically to have annotations for new classes. 

Thanks for this great work!

**Comment by krosaen** [comment]
Yes, I believe you could hack on the [Pascal VOC Loader](https://github.com/apache/incubator-mxnet/blob/master/example/rcnn/rcnn/dataset/pascal_voc.py) to expect different class names, and then have your VOC-like dataset match accordingly. One way to do this would be to map your modified file into the container using docker volumes.

Hope this helps, wish I could provide more explicit guidance but do not have the bandwidth atm.
